version: '3.8'

services:
  ms-cs-community:
    container_name: ms-cs-community
    # The official v2 Traefik docker image
    image: ms-cs-community:latest
    restart: always
    ports:
      # The HTTP port
      - '8001:9000'
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      MONGO_URL: ${MONGO_URL}
      BREVO_API_KEY: ${BREVO_API_KEY}
    networks:
      - applications-network
networks:
  applications-network:
    external: true
    name: applications-network
